name: Workflow Caller - Example

on:
  workflow_dispatch:
  pull_request:
    branches:
        - '**'

permissions:
    id-token: write
    contents: read

jobs:
  sample-reusable-workflow:
    uses: dvm191/az-modules/.github/workflows/sample-reusable-workflow.yaml@main
    with:
      echo: Hello
    secrets: inherit
