name: Reusable Workflow - Echo String

on:
  workflow_call:
    inputs:        
      echo:
        type: string
        description: 'echo out a string'
        required: true

permissions:
    id-token: write
    contents: read
          
defaults:
  run:
    shell: bash

jobs:
  echo-input:
    name: 'Echo Input'
    runs-on: "ubuntu-latest"
    steps:
      - name: Echo
        run: | 
          echo ${{inputs.echo}} - Step completed successfully! >> $GITHUB_STEP_SUMMARY
