name: Reusable Workflow - Echo String

on:
  workflow_call:
    inputs:        
      echo:
        type: string
        description: 'echo out a string'
        required: true

permissions:
    id-token: write
    contents: read
          
defaults:
  run:
    shell: bash

jobs:
  echo-input:
    name: 'Echo Input'
    runs-on: "ubuntu-latest"
    steps:
      - name: Echo
        run: |
          $output=${{inputs.echo}}      
          echo "summary<<${delimiter}" >> $GITHUB_OUTPUT
          echo "## Test Output" >> $GITHUB_OUTPUT
          echo "<details><summary>Click to expand</summary>" >> $GITHUB_OUTPUT
          echo "" >> $GITHUB_OUTPUT
          echo '```Echo' >> $GITHUB_OUTPUT
          echo "$output" >> $GITHUB_OUTPUT
          echo '```' >> $GITHUB_OUTPUT
          echo "</details>" >> $GITHUB_OUTPUT
          echo "${delimiter}" >> $GITHUB_OUTPUT
